### ISSUE TITLE
Use python 3

### ISSUE THREAD

**Issue by koopkaup** [qunfengdong/BLCA#11]
Some steps take enormously long time to run. Especially reading in blast output. Python version 3 has optimized dictionary and list functions, thus they run faster. I strongly suggest to update BLCA for python 3.

**Comment by yingeddi2008** [comment]
Hi Kristjan,

Thanks for taking an interest in using our software. 

And yes, you are right! We are in the process of improving our running speed, especially at the reading blastn output step. Your suggestion is highly appreciated. 
 
Best,

Huaiying (Eddi) Lin
