### ISSUE TITLE
 ValueError: max() arg is an empty sequence" error

### ISSUE THREAD

**Issue by aboffin** [qunfengdong/BLCA#13]
Hi,

I pulled the latest version of "2.blca_main.py", running it gives the error: 
"ValueError: max() arg is an empty sequence"

In addition, initially, I got "ERROR: clustalo is NOT in your PATH, please set up clustalo!" Installing crustal-omega solves the issue. 

The README file only specifies BLASTN and MUSCLE to be in the PATH but does not say anything about clustal-omega.

However, I get the "max() arg is an empty sequence error". 

```
python /Users/sen/git_repos/BLCA/2.blca_main.py -i otu_ungap.fasta \
 -r /Users/sen/git_repos/BLCA/db/16SMicrobial.ACC.taxonomy \
 -q /Users/sen/git_repos/BLCA/db/16SMicrobial;

clustalo is located in your PATH!
>  > Fasta file read in!
>  > Reading in taxonomy information! ....
blastn is located in your PATH!
> > Running blast!!
> > Blastn Finished!!
>  > read in blast file...
>  > blastn file opened
>  > blast output read in
>  > Start aligning reads...
Cut offs
('evalue:', 0.1, 'identity:', 90.0, 'coverage:', 0.85)
Traceback (most recent call last):
  File "/Users/sen/git_repos/BLCA/2.blca_main.py", line 329, in <module>
    mx=max(tmpdic.values())
ValueError: max() arg is an empty sequence
```

**Comment by yingeddi2008** [comment]
Hi Senthil,

Thanks for the feedback. I will make appropriate changes to the README file
and test on the updated package. Since we are accepting other
collaborators' contribution to the main function, it needs more testing
than usual to have smoothly-running software.

Thanks again for your support, I will get the software running as soon as
possible.

Eddi

**Comment by aboffin** [comment]
Hi Eddi,

Reverting back to an earlier commit seems to resolve the issue. Is it possible to revert back the last commit till you resolve the script and may be commit it once you are sure all tests pass? This will save headache for others who are downloading the latest (but non-working) version from GitHub.

Thanks,
Senthil

```
python /Users/sen/git_repos/BLCA/2.blca_main_aboffin.py -i otu_ungap.fasta -r /Users/sen/git_repos/BLCA/db/16SMicrobial.ACC.taxonomy -q /Users/sen/git_repos/BLCA/db/16SMicrobial
blastdbcmd is located in your PATH!
muscle is located in your PATH!
>  > Fasta file read in!!
>  > Reading in taxonomy information! ....
blastn is located in your PATH!
> > Running blast!!
> > Blastn Finished!!
>  > Read in blast output!
>> Taxonomy file generated!!
```

**Comment by yingeddi2008** [comment]
Hi Senthil,

I prepared a release of the previous version of the software at
https://github.com/qunfengdong/BLCA/releases. It is the python2.7
compatible one. I will update the README file accordingly. You can download
the source code, unzipp it. And it should be identical to the package
before the python 3 version.

Let me know if you have any further questions,

Thanks,

Eddi

**Comment by aboffin** [comment]
Thanks Eddi!

**Comment by ChouhanDheeraj** [comment]
> Hi,
> 
> I pulled the latest version of "2.blca_main.py", running it gives the error: "ValueError: max() arg is an empty sequence"
> 
> In addition, initially, I got "ERROR: clustalo is NOT in your PATH, please set up clustalo!" Installing crustal-omega solves the issue.
> 
> The README file only specifies BLASTN and MUSCLE to be in the PATH but does not say anything about clustal-omega.
> 
> However, I get the "max() arg is an empty sequence error".
> 
> ```
> python /Users/sen/git_repos/BLCA/2.blca_main.py -i otu_ungap.fasta \
>  -r /Users/sen/git_repos/BLCA/db/16SMicrobial.ACC.taxonomy \
>  -q /Users/sen/git_repos/BLCA/db/16SMicrobial;
> 
> clustalo is located in your PATH!
> >  > Fasta file read in!
> >  > Reading in taxonomy information! ....
> blastn is located in your PATH!
> > > Running blast!!
> > > Blastn Finished!!
> >  > read in blast file...
> >  > blastn file opened
> >  > blast output read in
> >  > Start aligning reads...
> Cut offs
> ('evalue:', 0.1, 'identity:', 90.0, 'coverage:', 0.85)
> Traceback (most recent call last):
>   File "/Users/sen/git_repos/BLCA/2.blca_main.py", line 329, in <module>
>     mx=max(tmpdic.values())
> ValueError: max() arg is an empty sequence
> ```
Hello @aboffin I am getting same error of 'clustalo is NOT in your PATH, please set up clustalo!' 
How can I resolve this ?
Can you please help me in this?



>

**Comment by qunfengdong** [comment]
Hello @ChouhanDheeraj, thank you for using BLCA. Could you try to install clustalo and add it to your PATH? Please let us know if you still have trouble doing that, thanks.
