### ISSUE TITLE
Dealing with subspecies in taxonomy mapping

### ISSUE THREAD

**Issue by dswan** [qunfengdong/BLCA#16]
Hi, in your docs it says that for a custom database you need:

> A taxonomy file with two columns, sequence ID in fasta file, and its taxonomy from superkingdom to species in the following format (The deliminator between the sequence ID and taxonomy information should be a tab [\t]):

I assumed that this meant you'd require a 7 level taxonomy tree. However if you actually use BLCA to run and parse the NCBI 16S database you get entries like:

```
NR_157602.1     subspecies:Leuconostoc mesenteroides subsp. jonggajibkimchii;species:Leuconostoc mesenteroides;genus:Leuconostoc;family:Leuconostocaceae;order:Lactobacillales;class:Bacilli;phylum:Firmicutes;superkingdom:Bacteria;
NR_159094.1     subspecies:Macrococcus caseolyticus subsp. hominis;species:Macrococcus caseolyticus;genus:Macrococcus;family:Staphylococcaceae;order:Bacillales;class:Bacilli;phylum:Firmicutes;superkingdom:Bacteria;
NR_115038.2     subspecies:Clavibacter michiganensis subsp. sepedonicus;species:Clavibacter michiganensis;genus:Clavibacter;family:Microbacteriaceae;order:Micrococcales;class:Actinobacteria;phylum:Actinobacteria;superkingdom:Bacteria;
```
Is the inclusion of **subspecies** here an issue? Or the desired behaviour? These have 8 levels of taxonomic information.

**Comment by dswan** [comment]
OK, well obviously I can test this, and I can see that for instance, if you submit the sequence for:

```>NR_074997.2 Leuconostoc gelidum subsp. gasicomitatum strain TB 1-10 16S ribosomal RNA, complete sequence```

to the default NCBI database, then it will return:

```superkingdom:Bacteria;100.0;phylum:Firmicutes;100.0;class:Bacilli;100.0;order:Lactobacillales;100.0;family:Leuconostocaceae;100.0;genus:Leuconostoc;100.0;species:Leuconostoc gelidum;100.0;```

based on the parsed taxonomy of:

```subspecies:Leuconostoc gelidum subsp. gasicomitatum;species:Leuconostoc gelidum;genus:Leuconostoc;family:Leuconostocaceae;order:Lactobacillales;class:Bacilli;phylum:Firmicutes;superkingdom:Bacteria;```

So I have a supplementary question - is subspecies ignored? Or is it just because there are  >1 entries for this particular subspecies sequence and the parent node is what is being reported?

**Comment by qunfengdong** [comment]
With our current version, subspecies is ignored; this is due to the fact
that the vast majority of taxonomic info at NCBI do not have subspecies
(only a few 16S entries have subspecies).  If you truly wants a version
that can also include subspecies as output, please let us know and we can
modify the script.

**Comment by dswan** [comment]
It would be nice for some genera but I suspect they'd be hard to tease apart anyway even with full-length 16S. I've incorporated the information into my custom DB but it doesn't matter that it's not going to be used, just wanted to check my understanding!

**Comment by qunfengdong** [comment]
In the next a few weeks, we will update BLCA and add an additional flag for
users who choose to output the subspecies information.  Our apology for
taking some time to get to it --- working on a few other projects now. But
please stay tuned.
