### ISSUE TITLE
weird sequence 

### ISSUE THREAD

**Issue by qinglong89** [qunfengdong/BLCA#21]
Hi Developer,

I had very weird situation met recently: other sequences were classified, but only one OTU sequence was not able to be run through (see the error message below). I pasted this sequence in this new issue. I am not exactly sure about this problem. But looks like several previous posts are related with this similar bug. Is this related with sequence pattern???

BLCA package was installed in August 2018.

$blastn -version
blastn: 2.7.1+
 Package: blast 2.7.1, build Oct 18 2017 19:57:24

$ muscle -version
MUSCLE v3.8.31 by Robert C. Edgar

$ python /home/qinglong/programs/BLCA/2.blca_main.py -i 3908.fa -r /home/qinglong/programs/BLCA/db/16SMicrobial.ACC.taxonomy -q /home/qinglong/programs/BLCA/db/16SMicrobial -o 3908.txt
##################################################################
blastdbcmd is located in your PATH!
muscle is located in your PATH!
>  > Fasta file read in!!
>  > Reading in taxonomy information! ....
blastn is located in your PATH!
> > Running blast!!
> > Blastn Finished!!
>  > Read in blast output!
Traceback (most recent call last):
  File "/home/qinglong/softwares/BLCA/2.blca_main.py", line 355, in <module>
    outout.write(le+":"+max(lexsum,key=lexsum.get)+";"+str(max(lexsum.values()))+";")
ValueError: max() arg is an empty sequence
###################################################################

>OTU_3908
ATTAGGCCAGCTACTGTCTGTTCGAGCCTGTGCTAGGTCAGACGCAGAGAGGTTGATCTC
GGGTGACGAGCGGCGGACGGGTGAGTAATGTCTGGGAAACTGCCTGATGGAGGGGGATAA
CTACTGGAAACGGTAGCTAATACCGCATAATGTCGCAAGACCAAAGTGGGGGACCTTCGG
GCCTCATGCCATCAGATGTGCCCAGATGGGATTAGCTAGTAGGTGGGGTAACGGCTCACC
TAGGCGACGATCCCTAGCTGGTCTGAGAGGATGACCAGCCACACTGGAACTGAGACACGG
TCCAGACTCCTACGGGAGGCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGC
AGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAA
GGCGATAAGGTTAATAACCTTGTCGATTGACGTTACCCGCAGAAGAAGCACCGGCTAACT
CCGTG

Thanks.

Qinglong

**Comment by qunfengdong** [comment]
Hi Qinglong:

Could you please try it with the latest version of BLCA?  The version in
2018 has been improved.

Qunfeng

**Comment by qinglong89** [comment]
Okay, thanks!
