### ISSUE TITLE
Treshold

### ISSUE THREAD

**Issue by bvalot** [qunfengdong/BLCA#25]
Hi,

I would have an idea for the thresold to use for filter classification. 
On mothur, I use 80. 

Thanks for this interesting  program.

**Comment by qunfengdong** [comment]
Hi,

Thank you for your interest.  Yes, we normally use 80 as the threshold in our own studies, although I think that it can be lower (there is no perfect threshold).

Cheers,
Qunfeng
---
Qunfeng_Dong, PhD
Pronouns: he|him|his
Director, Center for Biomedical Informatics
Professor, Department of Medicine
Stritch School of Medicine
Loyola University Chicago
2160 S. First Avenue
Maywood, Illinois 60153
Office: CTRE 459
qdong@luc.edu | 708-327-9004
http://ssom.luc.edu/cbmi/

On 10/7/20, 2:27 AM, <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I would have an idea for the thresold to use for filter classification.
On mothur, I use 80.

Thanks for this interesting program.

**Comment by bvalot** [comment]
Thank you.
