### ISSUE TITLE
Number of threads error

### ISSUE THREAD

**Issue by erin-d** [qunfengdong/BLCA#26]
Hi, 

I am trying to set up and use BLCA in a conda environment.  I have blast, muscle, and clustalo installed through the bioconda channel.

`python 1.subset_db_acc.py` works, but when I run `python 2.blca_main.py -i test.fasta` I get the following error, FATAL: Cannot change number of threads to 2. Clustal Omega was build without OpenMP support.`

I cannot seem to resolve this error, do you have any suggestions to fix this error?

Thanks,
Erin

![Screen Shot 2021-05-13 at 1 42 29 PM](https://user-images.githubusercontent.com/47370012/118199054-15e48280-b407-11eb-880c-b59325854257.png)

**Comment by YJulyXing** [comment]
Hello, Could you try add "-p 1" when you run python 2.blca_main.py and see what happens?

**Comment by erin-d** [comment]
This was successful, thank you!
