### ISSUE TITLE
TypeError: range() integer end argument expected, got float

### ISSUE THREAD

**Issue by duxuhao** [qunfengdong/BLCA#3]
Hi there,

Things were good when I did a couple runs using the default bootstrap value of 100. However when I tried a greater bootstrap value (200, 500 etc), very soon the process ended with the following messages:

blastdbcmd is located in your PATH
muscle is located in your PATH
blastn is located in your PATH
>>Running blast!!
>>Blastn Finished!!
> 1 > Read in blast output!
> 3 > Read in taxonomy information!
Traceback (most recent call last):
   File "/home/ubuntu/BLCA/2.blca_main.py", line 329, in <module>
      for j in range(nper):
TypeError: range() integer end argument expected, got float.

Please let me know if you need further details.

Cheers,
Eng

**Comment by yingeddi2008** [comment]
Hi Eng,

Thanks for checking out our program. I will look into it soon. 

Huaiying (Eddi) Lin

**Comment by yingeddi2008** [comment]
Hi Eng,

The bug should be fixed now. It was a type error. 

Thanks for using our program.

Please feel free to contact if the problem continues.

Eddi

**Comment by engchua** [comment]
Thanks Eddi, looking all good now.

Cheers,
Eng
