### ISSUE TITLE
##Taxomomic result at species, but The score is too small?

### ISSUE THREAD

**Issue by penglbio** [qunfengdong/BLCA#4]
I have taxonomy my 16s sequence, and I have got the result like below:

superkingdom:Bacteria;100.0;phylum:Bacteroidetes;100.0;class:Chitinophagia;100.0;order:Chitinophagales;100.0;family:Chitinophagaceae;100.0;genus:Flavisolibacter;47.0333333333;species:Flavisolibacter tropicus;47.0333333333;
--

--
I want to know the score of taxonomic rank at species just 47.0333333333 weather we can use or not. If we can't use the result. Which threshold is the best?

**Comment by qunfengdong** [comment]
Hi:

Those numbers represent confidence score.  100 means 100% confidence. 68
means 68% confidence score.  This score is very similar to what RDP
Classifier uses, in which it uses 80 as its default cutoff.   But quite
frankly, there is no perfect cutoff.   If you are dealing with a large
dataset, you can also consider 80 as your cutoff to be a vigorous cutoff .
But if you are analyzing a few sequences, I'd probably choose a cutoff of
60 and report the score as part of your results.  I hope that this helps.
Please feel free to ask if you still have questions.

Qunfeng
