### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by pmhenry** [qunfengdong/BLCA#5]
Hello!

I am trying to use this program on a custom database and am getting the following error:

```
python 2.blca_main.py -i mba91.fas -r tax_fusdb718.txt -q fusdb718

blastdbcmd is located in your PATH!
muscle is located in your PATH!
blastn is located in your PATH!
>> Running blast!!
>> Blastn Finished!!
> 1 > Read in blast output!
> 3 > Read in taxonomy information!
Traceback (most recent call last):
  File "2.blca_main.py", line 343, in <module>
    outout.write(le+":"+max(lexsum,key=lexsum.get)+";"+str(max(lexsum.values()))+";")
ValueError: max() arg is an empty sequence
```
the query fasta file (mba91.fas) has 10 sequences with short, unique sequence identifiers. The .blastn file shows they all have hits, but the .blca.out file only has:

```
10
```
10 is a sequence identifier. Please let me know if you need other information! Thanks!

**Comment by qunfengdong** [comment]
Hi:

Thanks for reporting the problem. 

Could you please send your query and database to qunfengd@gmail.com, so we can re-produce your error?

Thanks!

Qunfeng Dong

**Comment by pmhenry** [comment]
It looks like some programs hadn't loaded into my path properly -- now that they are it is working. Thanks!

**Comment by CaiWang0503** [comment]
> It looks like some programs hadn't loaded into my path properly -- now that they are it is working. Thanks!

how do you solve it, I have a same problem
