### ISSUE TITLE
Shebang should be python2 and not python

### ISSUE THREAD

**Issue by Eubel** [qunfengdong/BLCA#7]
Hi BCLA team,

I had to rename the shebang line of every python script from `#!/usr/bin/env python` to `#!/usr/bin/env python2` in order to get the scripts running with the required python version.
Many modern systems take `python3` as their default python.

Best regards,

Eubel

**Comment by yingeddi2008** [comment]
Hi Eubel,

Thanks for letting us know and I will include the note you mentioned in the instruction for future users.

Best regards,

Eddi
