### ISSUE TITLE
Clustal alignment tool instead of muscle

### ISSUE THREAD

**Issue by koopkaup** [qunfengdong/BLCA#8]
Because of the limitation in muscle alignment only showing maximum of 32 characters in the query ID whereas clustal (omega) doesn't have that limitation and the aligning speed is the same so I suggest switching from muscle to clustal. 

I modified the python code and used clustal omega and it seems to be working. 
My fasta headers are longer than 32 characters and I don't want to rename them to retain compatibility with other methods.

**Comment by qunfengdong** [comment]
Hi. Thanks for your suggestions. Yes, we are aware of the ID length restrictions with Muscle and I am glad that you have taken steps to try it with clustal instead. Do you mind sending us your modified code? We'd like to test it and consider your suggestions in the next release.  Thanks, Qunfeng

**Comment by qunfengdong** [comment]
I am away for a conference this week. If you'd like to share your code, please send it to qunfengd@gmail.com.
